### ISSUE TITLE
Maven adapter incompatible with latest HTTP version

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#108]
```
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at wtf.g4s8.rio.file.ReadSubscriberState.onComplete(ReadSubscriberState.java:76)
	at wtf.g4s8.rio.file.ReadRequest$Next.process(ReadRequest.java:127)
	at wtf.g4s8.rio.file.ReadTaskQueue.run(ReadTaskQueue.java:93)
	at wtf.g4s8.rio.file.CloseChanOnError.run(CloseChanOnError.java:25)
	at wtf.g4s8.rio.file.ErrorOnException.run(ErrorOnException.java:33)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at com.artipie.maven.http.MavenSlice.<init>(MavenSlice.java:73)
	at com.artipie.maven.http.MavenSlice.<init>(MavenSlice.java:63)
	at com.artipie.SliceFromConfig.build(SliceFromConfig.java:189)
	at com.artipie.SliceFromConfig.lambda$new$0(SliceFromConfig.java:126)
	... 15 more

```

**Comment by 0crat** [comment]
The job [#108](https://github.com/artipie/maven-adapter/issues/108) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/76855a6f-257a-431e-91c9-6e35d12ada6b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.5`

**Comment by g4s8** [comment]
Fixed

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
