### ISSUE TITLE
Maven proxy should handle missing artifacts without errors

### ISSUE THREAD

**Issue by olegmoz** [artipie/maven-adapter#211]
`RepoHead` class throws excpetion when receives 404 from remote. This is normal situation and should not cause exception
```
[ERROR] HttpClient@20135a4-60 com.artipie.maven.http.RepoHead: java.lang.IllegalStateException: Unsuccessful response status `404`
[INFO] HttpClient@20135a4-60 com.artipie.http.MainSlice: Failure: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unsuccessful response status `404`
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2179)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:143)
	at com.artipie.maven.http.RepoHead.lambda$head$0(RepoHead.java:76)
	at com.artipie.http.client.auth.AuthClientSlice.lambda$null$0(AuthClientSlice.java:88)
	at com.artipie.http.rs.RsWithStatus$ConWithStatus.accept(RsWithStatus.java:109)
	at com.artipie.http.rs.RsWithHeaders$ConWithHeaders.accept(RsWithHeaders.java:135)
	at com.artipie.http.rs.RsWithBody$ConWithBody.accept(RsWithBody.java:185)
	at com.artipie.http.rs.StandardRs.lambda$static$0(StandardRs.java:41)
	at com.artipie.http.rs.StandardRs.send(StandardRs.java:82)
	at com.artipie.http.rs.RsWithBody.send(RsWithBody.java:129)
	at com.artipie.http.rs.RsWithHeaders.send(RsWithHeaders.java:97)
	at com.artipie.http.rs.RsWithStatus.send(RsWithStatus.java:70)
	at com.artipie.http.Response$Wrap.send(Response.java:74)
	at com.artipie.http.client.jetty.JettyClientSlice.lambda$null$3(JettyClientSlice.java:123)
	at com.artipie.http.async.AsyncResponse.lambda$send$0(AsyncResponse.java:61)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.flowable.FlowableSingleSingle$SingleElementSubscriber.onComplete(FlowableSingleSingle.java:114)
	at org.eclipse.jetty.reactive.client.internal.AbstractSingleProcessor.onComplete(AbstractSingleProcessor.java:127)
	at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:57)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredSetOnce(SubscriptionHelper.java:202)
	at io.reactivex.internal.subscribers.StrictSubscriber.onSubscribe(StrictSubscriber.java:87)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.onHeaders(ResponseListenerProcessor.java:91)
	at org.eclipse.jetty.client.ResponseNotifier.notifyHeaders(ResponseNotifier.java:100)
	at org.eclipse.jetty.client.ResponseNotifier.notifyHeaders(ResponseNotifier.java:92)
	at org.eclipse.jetty.client.HttpReceiver.responseHeaders(HttpReceiver.java:322)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.headerComplete(HttpReceiverOverHTTP.java:284)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1206)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1503)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:200)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:141)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:75)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:156)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalStateException: Unsuccessful response status `404`
	at com.artipie.maven.http.RepoHead.lambda$head$0(RepoHead.java:72)
	... 49 more
```

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#211` is not assigned, can't get performer
