### ISSUE TITLE
Maven metadata version format

### ISSUE THREAD

**Issue by ChGen** [artipie/maven-adapter#255]
Checking artifacts in basic maven java project found dependency not handled correctly when uploading to Artipie (artipie/artipie:v0.27.2 ):

https://mvnrepository.com/artifact/classworlds/classworlds/1.1

Uploading with `mvn -V deploy:deploy-file -Dfile=... -DpomFile=...`

Generated metadata file (in Artipie repository) contains non-numeric version:

`classworlds/classworlds/1.1/meta/maven-metadata.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>classworlds</groupId>
  <artifactId>classworlds</artifactId>
  <versioning>
    <latest>1.1-alpha-2</latest>
    <release>1.1</release>
    <versions>
      <version>1.1-alpha-2</version>
      <version>1.1</version>
    </versions>
    <lastUpdated>20221021001021</lastUpdated>
  </versioning>
</metadata>
```

Exception in the artipie log:

```
NFO: List 'ChGen/maventest/classworlds/classworlds': 11
Oct 21, 2022 12:10:21 AM com.artipie.asto.LoggingStorage log
INFO: Value 'ChGen/maventest/.upload/classworlds/classworlds/1.1/meta/maven-metadata.xml': Optional[368]
Oct 21, 2022 12:10:21 AM com.artipie.asto.LoggingStorage log
INFO: Delete 'ChGen/maventest/.artipie-locks/classworlds/classworlds/bc94e971-31d7-4067-b054-111798fb31e0'
[ForkJoinPool.commonPool-worker-2] INFO com.artipie.http.MainSlice - Failure: java.util.concurrent.CompletionException: java.lang.NumberFormatException: For input string: "1-alpha-2"
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at com.artipie.MeasuredStorage$2$1.onComplete(MeasuredStorage.java:233)
	at org.cqfn.rio.channel.ReadSubscriberState.onComplete(ReadSubscriberState.java:77)
	at org.cqfn.rio.channel.ReadRequest$Next.process(ReadRequest.java:135)
	at org.cqfn.rio.channel.ReadTaskQueue.run(ReadTaskQueue.java:102)
	at org.cqfn.rio.channel.CloseChanOnError.run(CloseChanOnError.java:61)
	at org.cqfn.rio.channel.ErrorOnException.run(ErrorOnException.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "1-alpha-2"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.IntPipeline.toArray(IntPipeline.java:562)
	at com.artipie.maven.metadata.Version.stringVersionToIntArray(Version.java:62)
	at com.artipie.maven.metadata.Version.compareTo(Version.java:51)
	at com.artipie.maven.metadata.Version.compareTo(Version.java:33)
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
	at java.base/java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:698)
	at com.artipie.maven.metadata.MavenMetadata.versions(MavenMetadata.java:70)
	at com.artipie.maven.asto.AstoMaven.lambda$update$4(AstoMaven.java:91)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 15 more
```

**Comment by olenagerasimova** [comment]
@ChGen where did the version `1.1-alpha-2` come from?

**Comment by ChGen** [comment]
@olenagerasimova , I've prepared simple `pom.xml` (attached) for maven project and made `mvn clean install` with clean `.m2` cache. 
[pom.zip](https://github.com/artipie/maven-adapter/files/9850558/pom.zip)

**Comment by olenagerasimova** [comment]
@ChGen according to the attached pom version is `1.0` not `1.1-alpha-2`...

**Comment by ChGen** [comment]
@olenagerasimova , I tested it again, and it downloads 1.1 and its alpha version too:
```
[evgeny@EGRAMM16 ~wartipiebenchmarksloadtestshelloworld-src.zip](https://github.com/artipie/maven-adapter/files/9850990/evgeny%40EGRAMM16.wartipiebenchmarksloadtestshelloworld-src.zip)

drwxr-xr-x 2 evgeny evgeny 4096 Oct 24 13:09 1.1/
drwxr-xr-x 2 evgeny evgeny 4096 Oct 24 13:09 1.1-alpha-2/
```
