### ISSUE TITLE
Maven uploading exceptions

### ISSUE THREAD

**Issue by ChGen** [artipie/maven-adapter#256]
When uploading with `mvn deploy:deploy-file ...` I get intermittent exceptions. 
Typical exception is:
```
[ForkJoinPool.commonPool-worker-3] INFO com.artipie.http.MainSlice - Failure: java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.nio.file.NoSuchFileException: /var/artipie/.storage/data/ChGen/maventest/.upload/org/apache/commons/commons-lang3/3.1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.artipie.asto.ArtipieIOException: java.nio.file.NoSuchFileException: /var/artipie/.storage/data/ChGen/maventest/.upload/org/apache/commons/commons-lang3/3.1
	at com.artipie.asto.fs.FileStorage.deleteEmptyParts(FileStorage.java:258)
	at com.artipie.asto.fs.FileStorage.lambda$delete$12(FileStorage.java:173)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 6 more
Caused by: java.nio.file.NoSuchFileException: /var/artipie/.storage/data/ChGen/maventest/.upload/org/apache/commons/commons-lang3/3.1
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:440)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/java.nio.file.Files.list(Files.java:3792)
	at com.artipie.asto.fs.FileStorage.deleteEmptyParts(FileStorage.java:248)
	... 8 more
```

When simulation uploads with JMeter I get similar exceptions, but also a new one:
```
[ForkJoinPool.commonPool-worker-3] INFO com.artipie.http.MainSlice - Failure: java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: Failed to acquire lock.
Own: `.artipie-locks/org/apache/maven/maven-toolchain/0f03f797-9dc6-48ce-bc7f-a6e9e9c953be`
Others: `.artipie-locks/org/apache/maven/maven-toolchain/0f03f797-9dc6-48ce-bc7f-a6e9e9c953be`, `.artipie-locks/org/apache/maven/maven-toolchain/a415cd9d-d895-4659-b4c2-7d310da07594`
Not expired: `.artipie-locks/org/apache/maven/maven-toolchain/a415cd9d-d895-4659-b4c2-7d310da07594` ``
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at org.cqfn.rio.channel.ReadSubscriberState.onComplete(ReadSubscriberState.java:77)
	at org.cqfn.rio.channel.ReadRequest$Next.process(ReadRequest.java:135)
	at org.cqfn.rio.channel.ReadTaskQueue.run(ReadTaskQueue.java:102)
	at org.cqfn.rio.channel.CloseChanOnError.run(CloseChanOnError.java:61)
	at org.cq
[m2-up-jmeter.zip](https://github.com/artipie/maven-adapter/files/9839568/m2-up-jmeter.zip)
[mvn-deploy-file-uploads-exceptions.zip](https://github.com/artipie/maven-adapter/files/9839570/mvn-deploy-file-uploads-exceptions.zip)
fn.rio.channel.ErrorOnException.run(ErrorOnException.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.artipie.asto.ArtipieIOException: java.io.IOException: Failed to acquire lock.
Own: `.artipie-locks/org/apache/maven/maven-toolchain/0f03f797-9dc6-48ce-bc7f-a6e9e9c953be`
Others: `.artipie-locks/org/apache/maven/maven-toolchain/0f03f797-9dc6-48ce-bc7f-a6e9e9c953be`, `.artipie-locks/org/apache/maven/maven-toolchain/a415cd9d-d895-4659-b4c2-7d310da07594`
Not expired: `.artipie-locks/org/apache/maven/maven-toolchain/a415cd9d-d895-4659-b4c2-7d310da07594` ``
	at com.artipie.asto.lock.storage.Proposals.lambda$null$3(Proposals.java:85)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 14 more
Caused by: java.io.IOException: Failed to acquire lock.
Own: `.artipie-locks/org/apache/maven/maven-toolchain/0f03f797-9dc6-48ce-bc7f-a6e9e9c953be`
Others: `.artipie-locks/org/apache/maven/maven-toolchain/0f03f797-9dc6-48ce-bc7f-a6e9e9c953be`, `.artipie-locks/org/apache/maven/maven-toolchain/a415cd9d-d895-4659-b4c2-7d310da07594`
Not expired: `.artipie-locks/org/apache/maven/maven-toolchain/a415cd9d-d895-4659-b4c2-7d310da07594` ``
	at com.artipie.asto.ArtipieIOException.<init>(ArtipieIOException.java:59)
	... 16 more
```

This all looks like some kind of concurrency/synchronization kind of issue to me.
Logs for both cases are attached.

**Comment by olenagerasimova** [comment]
I've fixed several issues in asto connecting with "file not found error" recently, so let's update the dependencies at first and see what happen.
