### ISSUE TITLE
Gradle plugin fails to publish

### ISSUE THREAD

**Issue by AndreasErne** [artipie/maven-adapter#269]
Publishing a gradle plugin to my artipie repository behaves very odd and fails most of the time with the following client side error message:
`11:34:57: Executing 'clean publish --no-build-cache'...

> Task :clean
> Task :pluginDescriptors
> Task :processResources
> Task :sourcesJar
> Task :generatePomFileForPluginMavenPublication
> Task :generatePomFileForGradlePluginPluginPluginMarkerMavenPublication
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :classes
> Task :jar
> Task :inspectClassesForKotlinIC
> Task :generateMetadataFileForPluginMavenPublication
Download https://artipie.ieffects.com//snapshots-local/com/ieffects/gradle-tools/gradleplugin-plugin/3.0.0-SNAPSHOT/maven-metadata.xml, took 180 ms (1.18 kB)
> Task :publishPluginMavenPublicationToMavenRepository FAILED
11 actionable tasks: 11 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishPluginMavenPublicationToMavenRepository'.
> Failed to publish publication 'pluginMaven' to repository 'maven'
   > Could not PUT 'https://artipie.ieffects.com//snapshots-local/com/ieffects/gradle-tools/gradleplugin-plugin/maven-metadata.xml.sha1'. Received status code 500 from server: Internal Server Error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
11:35:03: Execution finished 'clean publish --no-build-cache'.`

On the server, the following exception is logged:
`artipie        | [ForkJoinPool.commonPool-worker-53] INFO com.artipie.http.MainSlice - Failure: java.util.concurrent.CompletionException: com.vdurmont.semver4j.SemverException: Invalid version (no major version): com.ieffects.gradle-tools.gradleplugin-plugin.gradle.plugin
artipie        | 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
artipie        | 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
artipie        | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
artipie        | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie        | 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
artipie        | 	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
artipie        | 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
artipie        | 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
artipie        | 	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
artipie        | 	at com.artipie.micrometer.MicrometerPublisher$MicrometerSubscriber.onComplete(MicrometerPublisher.java:109)
artipie        | 	at org.cqfn.rio.channel.ReadSubscriberState.onComplete(ReadSubscriberState.java:77)
artipie        | 	at org.cqfn.rio.channel.ReadRequest$Next.process(ReadRequest.java:135)
artipie        | 	at org.cqfn.rio.channel.ReadTaskQueue.run(ReadTaskQueue.java:102)
artipie        | 	at org.cqfn.rio.channel.CloseChanOnError.run(CloseChanOnError.java:61)
artipie        | 	at org.cqfn.rio.channel.ErrorOnException.run(ErrorOnException.java:58)
artipie        | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
artipie        | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
artipie        | 	at java.base/java.lang.Thread.run(Thread.java:833)
artipie        | Caused by: com.vdurmont.semver4j.SemverException: Invalid version (no major version): com.ieffects.gradle-tools.gradleplugin-plugin.gradle.plugin
artipie        | 	at com.vdurmont.semver4j.Semver.<init>(Semver.java:61)
artipie        | 	at com.artipie.maven.metadata.Version.compareTo(Version.java:30)
artipie        | 	at com.artipie.maven.metadata.Version.compareTo(Version.java:13)
artipie        | 	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
artipie        | 	at java.base/java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
artipie        | 	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
artipie        | 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
artipie        | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
artipie        | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
artipie        | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
artipie        | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
artipie        | 	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
artipie        | 	at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:698)
artipie        | 	at com.artipie.maven.metadata.MavenMetadata.versions(MavenMetadata.java:51)
artipie        | 	at com.artipie.maven.asto.AstoMaven.lambda$update$4(AstoMaven.java:71)
artipie        | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
artipie        | 	... 15 more`

See attachment for full log.

I assume the complex gradle plugin publication procedure might cause this problem. A gradle plugin publication consists of two artifacts, the plugin itself and a so called "marker" publication. I guess these publications interfere somehow on the file storage.

The issue occurs randomly:
* If there is no plugin artifact on artipie, the very first publication works fine most of the time
* Repeated publications for the same artifact suddenly fail and can't be fixed by another publication
* To make sure that the client side gradle build does not contribute to the issue I run always "gradle clean publish --no-build-cache"

**Comment by AndreasErne** [comment]
This is the full log: 
[gradle-publication-failure.log](https://github.com/artipie/maven-adapter/files/12558241/gradle-publication-failure.log)
